apiVersion: v1
kind: Service
metadata:
  name: flask-app-service  # Name of the service
  namespace: prod
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP for internal access
  ports:
    - port: 80  # The port the service is exposed on
      targetPort: 5000  # The target port on the container
  selector:
    app: flask-app  # Selects the pods with label app=flask-app
